dist:
  name: otelcol-sonifier
  description: "OpenTelemetry Collector with Sonifier Extension"
  output_path: ./otelcol-sonifier
  version: 0.131.0
  otelcol_version: 0.131.0

replaces:
  - github.com/gemini/sonifierextension => ../sonifierextension

extensions:
  - gomod: github.com/gemini/sonifierextension v0.0.0-00010101000000-000000000000

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.131.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.131.0

processors:

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.131.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.37.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.37.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.37.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.37.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.37.0