dist:
  name: otelcol-sonifier
  description: "OpenTelemetry Collector with the Sonifier exporter"
  output_path: ./otelcol-sonifier

exporters:
  - gomod: github.com/theletterf/otel-sonifier/sonifierexporter v0.0.0
    path: ./sonifierexporter

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.162.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.68.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.68.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.68.0
