receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  sonifier:
    # Web UI and WebSocket stream.
    endpoint: localhost:44444

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [sonifier]
    metrics:
      receivers: [otlp]
      exporters: [sonifier]
    logs:
      receivers: [otlp]
      exporters: [sonifier]
